title: Essential Mathematics for Chemical Engineers
author: Michael P. Howard
copyright: "2025"
email: mphoward@auburn.edu

execute:
  execute_notebooks: force

html:
  baseurl: ""
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - replacements
    - smartquotes

repository:
  url: https://github.com/mphowardlab/essential-math
  branch: main
