title: Essential Mathematics for Chemical Engineers
author: Michael P. Howard
copyright: "2025"
email: mphoward@auburn.edu

exclude_patterns: [.github/*]

execute:
  execute_notebooks: force

html:
  baseurl: https://mphowardlab.github.io/essential-math
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - replacements
    - smartquotes

repository:
  url: https://github.com/mphowardlab/essential-math
  branch: main

sphinx:
  local_extensions:
    example_admonition: _extensions
  config:
    mathjax3_config:
      tex:
        macros:
          "d": ["{\\operatorname{d}\\!{#1}}", 1]
          "dd": ["{\\d{}^{#1} #2 \\over \\d{#3}^{#1}}", 3]
          "pp": ["{\\partial^{#1} #2 \\over \\partial #3^{#1}}", 3]
          "td": ["{\\left(\\pp{#1}{#2}{#3} \\right)_{#4}}", 4]
          "vv": ["\\mathbf{#1}", 1]
